name: Destroy

on:
  workflow_run:
    workflows: ["CD"]
    types:
      - completed

# on:
#   workflow_dispatch: # This allows the workflow to be triggered manually

jobs:
  terraform:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
          terraform_wrapper: false
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          aws-access-key-id: ${{ secrets.ASHWANI_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ASHWANI_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.ASHWANI_AWS_REGION }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan Destroy
        id: plan
        run: terraform plan -destroy -no-color

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
